name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
permissions:
  id-token: write
  contents: read
    
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}

jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18,20]
        os: [ubuntu-latest]
        exclude:
          - nodejs_version: 18
            os: macos-latest
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version ${{ matrix.nodejs_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.nodejs_version }}
    
    - name: Cache NPM Dependancy
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json')}}
     
    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      id: unit_testing_step
      run: npm test
      
    - name: Archive Test Result
      if: steps.unit_testing_step.outcome == 'falure' || 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Test-Result-${{ matrix.nodejs_version }}-${{ matrix.os }}- ${{ github.run_id }}
        path: test-results.xml


  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache NPM Dependancy
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json')}}
    
    - name: Install Dependencies
      run: npm install

    - name: Check Code Coverage
      continue-on-error: true
      run: npm run coverage
        
    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-result
        path: coverage
        retention-days: 5


  docker:
    name: containerization
    needs: [unit-testing, code-coverage]
    runs-on:  ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ap-south-1
        role-to-assume: arn:aws:iam::992293216837:role/github-action-oidc-Role-xta7NbBBHjdI

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: study/demo-repo
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}

    - name: Docker Image Testing
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker images
        docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=${{ env.MONGO_URI }} \
          -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
          -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
        
        export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
        echo $IP

        echo Testing Image URL using wget
        wget -q -o - 127.0.0.1:3000/live | grep live